package com.fm.common.model;

import com.fm.common.model.base.BaseBank;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bank extends BaseBank<Bank> {
	public static final Bank dao = new Bank();
}
