package com.fm.common.model;

import com.fm.common.model.base.BaseReceipt;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Receipt extends BaseReceipt<Receipt> {
	public static final Receipt dao = new Receipt();
}
