package com.fm.common.model;

import com.fm.common.model.base.BaseUserFriend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserFriend extends BaseUserFriend<UserFriend> {
	public static final UserFriend dao = new UserFriend();
}
