package com.fm.common.model;

import java.util.List;

import com.fm.common.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User();
	
	public List<User> findAll() {
		return find("select * from t_user");
	}
}
